# Generated by Django 3.2.3 on 2021-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_links',
            field=models.CharField(default='www.youtube.com', max_length=255),
            preserve_default=False,
        ),
    ]
