# Generated by Django 3.2.3 on 2021-05-27 20:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('red', 'red'), ('fuji  ', 'fuji'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('comedy', 'comedy'), ('coding', 'coding'), ('reviews', 'reviews'), ('film making ', 'film making'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small up to 10 people'), ('medium', 'medium up to 50 people')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
