# Generated by Django 3.2.3 on 2021-05-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210527_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='youtube_links',
            field=models.CharField(default='9b4RZGHKpDE', max_length=255),
            preserve_default=False,
        ),
    ]
